# Reference for compose file: https://docs.docker.com/compose/compose-file/#compose-file
# To connect to this instance from another container: 172.17.0.1 (You can check it by calling ifconfig command and get the docker's ip address)

name: mysql-advanced-course
services:
  db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678 # just for dev/study
      MYSQL_DATABASE: mavenfuzzyfactory
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./.db-setup:/docker-entrypoint-initdb.d
volumes:
  db-data: